CREATE TABLE IF NOT EXISTS "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "packages" ("id" integer not null primary key autoincrement, "nombre" varchar not null, "precio" varchar not null, "descripcion" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "packeages" ("id" integer not null primary key autoincrement, "nombre" varchar not null, "precio" varchar not null, "descripcion" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "users" ("id" integer not null primary key autoincrement, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "password_resets" ("email" varchar not null, "token" varchar not null, "created_at" datetime);
CREATE INDEX "password_resets_email_index" on "password_resets" ("email");
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer not null primary key autoincrement, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime default CURRENT_TIMESTAMP not null);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer not null primary key autoincrement, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "eventos" ("id" integer not null primary key autoincrement, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "usuarios" ("id" integer not null primary key autoincrement, "nombre" varchar not null, "nombre_de_usuario" varchar not null, "cargo" varchar not null, "clave" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "grupopaquetes" ("id" integer not null primary key autoincrement, "nombre" varchar not null, "precio" varchar not null, "descripcion" varchar not null, "created_at" datetime, "updated_at" datetime);
INSERT INTO migrations VALUES(8,'2023_04_18_001714_create_packages_table',2);
INSERT INTO migrations VALUES(23,'2023_04_18_002626_create_packeages_table',3);
INSERT INTO migrations VALUES(32,'2014_10_12_000000_create_users_table',4);
INSERT INTO migrations VALUES(33,'2014_10_12_100000_create_password_reset_tokens_table',4);
INSERT INTO migrations VALUES(34,'2014_10_12_100000_create_password_resets_table',4);
INSERT INTO migrations VALUES(35,'2019_08_19_000000_create_failed_jobs_table',4);
INSERT INTO migrations VALUES(36,'2019_12_14_000001_create_personal_access_tokens_table',4);
INSERT INTO migrations VALUES(37,'2023_03_21_005119_create_eventos_table',4);
INSERT INTO migrations VALUES(38,'2023_04_15_194742_create_usuarios_table',4);
INSERT INTO migrations VALUES(39,'2023_04_18_004558_create_grupopaquetes_table',4);
